#web_profiler:
#    toolbar:              false
#    intercept_redirects:  false
#    excluded_ajax_paths:  ^/(app(_[\\w]+)?\\.php/)?_wdt

#web_profiler:
#    toolbar: true
#    intercept_redirects: false